---
output: word_document
---

Impact on Information Resources

The CAP LTER added eight new data sets to its publicly available data holdings, six of which were reconfigurations of existing data sets to lend more clarity to the information structure; another seventeen data sets were revised or updated during the reporting year. A wew data set of note is the first publication from the CAP LTER's monitoring of water quality in the Tempe Town Lake, a man-made lake in the bed of the Salt River . All metadata are encoded in the XML-based Ecological Metadata Language (EML), with data and metadata available via both the CAP LTER data catalog on the project website and the LTER Network Information System catalog. 

The CAP LTER Information Manager and Julie Ann Wrigley Global Institute of Sustainability (GIOS) informatics team strive continuously to improve the presentation, utility, and management of CAP LTER information resources. Notable improvements for this reporting year include:

* S. Earl and former CAP LTER Information Manager (P. Tarrant) taught a course on research data management at Arizona State University in the spring of 2017. This course provided graduate students, including students actively involved with the CAP LTER, with a greater awareness of the importance of data curation, and the skills and tools to more effectively manage their research data. On the heels of strong reviews, S. Earl and P. Tarrant will teach this course again in the spring of 2018.
* The CAP LTER created a GitHub organization to accommodate centralized storage of code and other information resources. Version control provides a linear history of improvements and changes to informatics workflows and resources, and the public repositories may provide helpful contributions to other institutions with similar data-processing requirements.
* The GIOS informatics team transitioned all digital resources from campus-based servers to cloud environments. Servers, and web and informatics resources are now hosted on Amazon, and file-based resources are hosted on Dropbox. These transitions provide greater resilience, utility, and dependability at a reduced cost. 
* Proposed to coincide with the start of the start of a successful renewal proposal is the formation of an advisory committee consisting of a CAP LTER principal investigator, graduate student, and project staff member to guide the direction and implementation of information management at the CAP LTER. Input from the planned Information Management Advisory Committee (IMAC) is sought to provide (1) insight regarding information management tools and resources that project participants will find most useful and, thus, aid research production, and (2) perspectives from a diversity of backgrounds and areas of expertise to shape data products such that they are maximally discoverable, decipherable, and usable.
 
The CAP LTER is committed to making a strong contribution to informatics within the LTER network. The CAP LTER Information Manager (S. Earl) participates in all network information meetings and activities. He is an elected officer of the LTER Information Management Executive Committee, chaired the LTER Information Managers Skillset and Training Resources working group, and is a member of a working group tasked with revising the LTER Information Management Committee Terms-of-Reference (by-laws). In addition, S. Earl serves on the Environmental Data Initiative (EDI) Data Checks Committee, which oversees quality control checks implemented in the PASTA+ system (the engine that helps to ensure the integrity of data sets submitted to the LTER and EDI data portals).
