---
output: word_document
---

Impact on Information Resources

The CAP LTER added eight new data sets to its publicly available data holdings, and updated another seventeen existing data sets during the reporting year. A new data set of note is the first publication from the CAP LTER's monitoring of water quality in the Tempe Town Lake, a man-made reservoir constructed in the bed of the Salt River designed as a recreational resource and focal point for development. In keeping with the CAP LTER's efforts to continually improve the discoverability and utility of its data, six of the eight new data sets were generated from reconfigurations of existing data sets that reflect several of the CAP LTER's signature long-term monitoring programs. All CAP LTER data set metadata are encoded in the XML-based Ecological Metadata Language (EML), with data and metadata available through both the CAP LTER data catalog on the project website and the Environmental Data Initiative (EDI) data portal. 

The CAP LTER Information Manager and Julie Ann Wrigley Global Institute of Sustainability (GIOS) informatics team strive continuously to improve the presentation, utility, and management of CAP LTER information resources. Notable improvements for this reporting year include:

* The current (S. Earl) and former (P. Tarrant) CAP LTER Information Managers taught a course on research data management at Arizona State University in the spring of 2017. This course provided graduate students, including students actively involved with the CAP LTER, with a greater awareness of the importance of data curation, and the skills and tools needed to more effectively manage their research data. On the heels of strong reviews, S. Earl and P. Tarrant will teach this course again in the spring of 2018.
* CAP LTER managers and technicians completed the migration of digital resources from university servers and personal computers to Dropbox. This transition provides greater resilience, utility, interoperability, and dependability at a reduced cost to CAP LTER's host institution (GIOS).
 
The CAP LTER is committed to making a strong contribution to informatics within the LTER Network and the ecological sciences generally. The CAP LTER Information Manager (S. Earl) participates in all network information meetings and activities, is an elected officer of the LTER Information Management Executive Committee (IM Exec), chaired an LTER Information Management Committee (IMC) working group that generated training guidelines for new Information Managers, and served on a working group that revised the IMC's Terms-of-Reference (by-laws). In addition, S. Earl serves on the Environmental Data Initiative (EDI) Data Checks Committee, which oversees quality control checks implemented in the PASTA+ system (the engine that helps to ensure the integrity of data sets submitted to the LTER and EDI data portals), and is an information manager on a NCEAS Synthesis Working Group studying Soil Organic Matter dynamics.
