---
output: word_document
  # word_document:
  #   reference_docx: "data-inventory-format-reference.docx"
fontfamily: Times New Roman
fontsize: 11pt
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r libraries, include=FALSE}
library(tidyverse)
library(xml2)
library(httr)
library(tools)
library(pander)
library(rcrossref)
# library(knitr)
```


```{r pastaQuery, include=FALSE}

pastaQuery <- function(qr) {

  queryResult <- GET("https://pasta.lternet.edu/package/search/eml", query = list(defType='edismax',
                                                                                  q=qr,
                                                                                  fq="scope:(knb-lter-cap)",
                                                                                  fq="-scope:ecotrends",
                                                                                  fq="-scope:lter-landsat*",
                                                                                  fl='*', sort="score,desc",
                                                                                  sort="packageid,asc",
                                                                                  debug="false",
                                                                                  start="0",
                                                                                  rows="1000"))
  
  
  # PASTA+ query results to tibble
  
  parsedContent <- content(queryResult, 'parsed', encoding="UTF-8") # yields class "xml_document" "xml_node"
  
  xmlContents <- xml_contents(parsedContent)
  
  # authors
  
  rows <- parsedContent %>%
    xml_find_all(".//document/authors") %>%
    map(~ xml_find_all(.x, xpath = "author"))
  
  
  rows_df <- data_frame(row = seq_along(rows),nodeset = rows)
  
  cells_df <- rows_df %>%
    mutate(col_name_raw = nodeset %>% map(~ xml_name(.)),
           cell_text = nodeset %>% map(~ xml_text(.)),
           i = nodeset %>% map(~ seq_along(.))) %>%
    select(row, i, col_name_raw, cell_text) %>%
    unnest()
  
  # need to convert authors format to Last, F. M.
  cells_df <- cells_df %>% 
    mutate(cell_text = gsub(",", "", cell_text)) %>% 
    separate(cell_text, c("last", "first", "middle"), sep = "\\s", remove = T) %>% 
    mutate(
      # trim whitespace
      last = str_trim(last, side = c("both")),
      first = str_trim(first, side = c("both")),
      middle = str_trim(middle, side = c("both")),
      # first and middle to initial
      first = str_extract(first, "[A-z]{1,1}"),
      middle = str_extract(middle, "[A-z]{1,1}")
    ) %>% 
    mutate(
      cell_text = case_when(
        (i >= 2 & is.na(middle)) ~ paste0(first, ". ", last),
        (i >= 2 & !is.na(middle)) ~ paste0(first, ". ", middle, ". ", last),
        (i == 1 & is.na(middle)) ~ paste0(last, " ", first, "."),
        (i == 1 & !is.na(middle)) ~ paste0(last, " ", first, ". ", middle, ".")
      )
    ) %>%
    select(-last, -first, -middle)
  
  auth_cast <- cells_df %>%
    group_by(row) %>%
    summarise(auths = paste(cell_text, collapse = ", "))
  
  
  # keywords
  
  rows <- parsedContent %>%
    xml_find_all(".//document/keywords") %>%
    map(~ xml_find_all(.x, xpath = "keyword"))
  
  rows_df <- data_frame(row = seq_along(rows),
                        nodeset = rows)
  
  cells_df <- rows_df %>%
    mutate(col_name_raw = nodeset %>% map(~ xml_name(.)),
           cell_text = nodeset %>% map(~ xml_text(.)),
           i = nodeset %>% map(~ seq_along(.))) %>%
    select(row, i, col_name_raw, cell_text) %>%
    unnest()
  
  # associate keyword with CRA
  cells_df <- cells_df %>% 
    mutate(
      cell_text = tolower(cell_text),
      # these are mapping to the LTER core areas but Dan wants to use a CAP'ified version of these (below)
      # CRA = case_when(
      #   grepl("primary production", cell_text, ignore.case = T) ~ "PP",
      #   grepl("population", cell_text, ignore.case = T) ~ "PS",
      #   grepl("movement of \\borganic\\b", cell_text, ignore.case = T) ~ "MoOM",
      #   grepl("movement of \\binorganic\\b", cell_text, ignore.case = T) ~ "MoIM",
      #   grepl("disturbance", cell_text, ignore.case = T) ~ "DP",
      #   grepl("landuse|land-use|land use", cell_text, ignore.case = T) ~ "LULCC",
      #   grepl("\\bhuman-environment\\b|\\bhuman environment\\b", cell_text, ignore.case = T) ~ "HEI" # also matched 'human environment feedback'
      # )) %>% 
      # CAP'ified core areas
      # PP ~ Primary Production
      # PC ~ Population and Communities
      # OMD ~ Organic Matter Dynamics
      # ND ~ Nutrient Dynamics
      # DP ~ Disturbance Processes
      # LULCC ~ LULCC
      # SESD ~ Social-Ecological Systems Dynamics (LTER::Human Environment Interactions)
      CRA = case_when(
        grepl("primary production", cell_text, ignore.case = T) ~ "PP",
        grepl("population", cell_text, ignore.case = T) ~ "PC",
        grepl("movement of \\borganic\\b", cell_text, ignore.case = T) ~ "OMD",
        grepl("movement of \\binorganic\\b", cell_text, ignore.case = T) ~ "ND",
        grepl("disturbance", cell_text, ignore.case = T) ~ "DP",
        grepl("landuse|land-use|land use", cell_text, ignore.case = T) ~ "LULCC",
        grepl("\\bhuman-environment\\b|\\bhuman environment\\b", cell_text, ignore.case = T) ~ "SESD" # also matched 'human environment feedback'
      )) %>% 
    filter(!is.na(CRA)) %>%
    distinct(row, CRA) %>%
    group_by(row) %>% 
    mutate(
      i = seq_along(row),
      col_name_raw = "keyword"
      ) %>% 
    select(row, i, col_name_raw, CRA)
  
  key_cast <- cells_df %>%
    group_by(row) %>%
    summarise(keys = paste(CRA, collapse = ", "))
  
  # put it all together
  
  queryResultTibble <-
    tibble( 
      packageid = xmlContents %>% xml_find_all("packageid") %>% xml_text(),
      title = xmlContents %>% xml_find_all("title") %>% xml_text(),
      # we only need the org for cases when the author is not an individual, so,
      # for those, we can use xml_find_first on the parsedContent sensu below
      orgs = parsedContent %>% xml_find_all(".//document") %>% xml_find_first("organizations") %>% xml_text(),
      pubdate = xmlContents %>% xml_find_all("pubdate") %>% xml_text(),
      dates = paste(xmlContents %>% xml_find_all("begindate") %>% xml_text(), " to ", xmlContents %>% xml_find_all("enddate") %>% xml_text()),
      doi = paste(xmlContents %>% xml_find_all("doi") %>% xml_text())) %>%
    rowid_to_column('row') %>%
    left_join(auth_cast, by = c('row')) %>%
    left_join(key_cast, by = c('row')) %>%
    mutate(sort_column = as.numeric(str_extract(packageid, "\\d+\\.\\d+"))) %>% 
    arrange(sort_column) %>% 
    select(PackageID = packageid,
           Title = title,
           CRAs = keys,
           Originators = auths,
           Orgs = orgs,
           # Dates = dates, # not needed
           DOI = doi,
           pubd = pubdate) %>% 
    mutate(Title = gsub("\n\\s{2,}", " ", Title))
  
  return (queryResultTibble)
  
}

```


```{r query_cap_datasets, include=FALSE}

capData <- pastaQuery("*:*")

```


```{r format_table, include=FALSE}

# example EDI citation that we will match:
# Childers D., N. Grimm, D. Hope, J. Kaye, C. Martin, N. McIntyre, J. Stutz.
# 2018. Ecological Survey of Central Arizona: a survey of key ecological
# indicators in the greater Phoenix metropolitan area and surrounding Sonoran
# desert, ongoing since 1999. Environmental Data Initiative.
# http://dx.doi.org/10.6073/pasta/0669ee6a71b24abb1ae3827f4ee77f6d. Dataset
# accessed 2/21/2018.

formatted_data <- capData %>% 
  mutate(
    dataset_auths = case_when(
      is.na(Originators) ~ Orgs,
      !is.na(Originators) ~ Originators
    ), # when there is not an author, use the org for the author
    citation = paste0(dataset_auths, ". ", pubd, ". ", Title, ". Environmental Data Initiative. ", DOI, ".")
  ) %>% 
  select(PackageID, citation, CRAs) %>% 
  mutate(
    citation = gsub("\\.\\.", "\\.", citation), # fix double-period in single-author datasets
    citation = gsub("\\. \\.", "\\.", citation), # fix period-space-period in some datasets
    CRAs = ifelse(grepl("E-Atlas", citation), NA, CRAs) # remove core area from the E-Atlas datasets
  )

```

```{r dataset_tweaks, include=FALSE}

# manually edit CRAs as appropriate

vetted_data <- formatted_data %>% 
  mutate(
    CRAs = ifelse(grepl("27.9", PackageID), NA, CRAs),
    CRAs = ifelse(grepl("41.13", PackageID), "PC", CRAs),
    CRAs = ifelse(grepl("p.45.9", PackageID), "SESD", CRAs),
    CRAs = ifelse(grepl("46.15", PackageID), "PC", CRAs),
    CRAs = ifelse(grepl("49.8", PackageID), "ND", CRAs),
    CRAs = ifelse(grepl("p.56.9", PackageID), "LULCC", CRAs),
    CRAs = ifelse(grepl("p.64.10", PackageID), "LULCC", CRAs),
    CRAs = ifelse(grepl("p.65.10", PackageID), "LULCC", CRAs),
    CRAs = ifelse(grepl("p.66.10", PackageID), "LULCC", CRAs),
    CRAs = ifelse(grepl("113", PackageID), "LULCC", CRAs),
    CRAs = ifelse(grepl("117", PackageID), "PC", CRAs),
    CRAs = ifelse(grepl("120", PackageID), "PC", CRAs),
    CRAs = ifelse(grepl("156", PackageID), NA, CRAs),
    CRAs = ifelse(grepl("158", PackageID), NA, CRAs),
    CRAs = ifelse(grepl("159", PackageID), "PC", CRAs),
    CRAs = ifelse(grepl("160", PackageID), "PC", CRAs),
    CRAs = ifelse(grepl("166", PackageID), NA, CRAs),
    CRAs = ifelse(grepl("220", PackageID), NA, CRAs),
    CRAs = ifelse(grepl("223", PackageID), "LULCC", CRAs),
    CRAs = ifelse(grepl("224", PackageID), NA, CRAs),
    CRAs = ifelse(grepl("226", PackageID), NA, CRAs),
    CRAs = ifelse(grepl("229", PackageID), "LULCC", CRAs),
    CRAs = ifelse(grepl("230", PackageID), "LULCC", CRAs),
    CRAs = ifelse(grepl("232", PackageID), "LULCC", CRAs),
    CRAs = ifelse(grepl("245", PackageID), NA, CRAs),
    CRAs = ifelse(grepl("247", PackageID), NA, CRAs),
    CRAs = ifelse(grepl("248", PackageID), "LULCC", CRAs),
    CRAs = ifelse(grepl("250", PackageID), "LULCC", CRAs),
    CRAs = ifelse(grepl("254", PackageID), NA, CRAs),
    CRAs = ifelse(grepl("257", PackageID), NA, CRAs),
    CRAs = ifelse(grepl("258", PackageID), NA, CRAs),
    CRAs = ifelse(grepl("261", PackageID), NA, CRAs),
    CRAs = ifelse(grepl("266", PackageID), "PC", CRAs),
    CRAs = ifelse(grepl("268", PackageID), "PC", CRAs),
    CRAs = ifelse(grepl("269", PackageID), "LULCC", CRAs),
    CRAs = ifelse(grepl("270", PackageID), "ND, OMD", CRAs),
    CRAs = ifelse(grepl("271", PackageID), "ND, OMD", CRAs),
    CRAs = ifelse(grepl("272", PackageID), "LULCC", CRAs),
    CRAs = ifelse(grepl("273", PackageID), "PC", CRAs),
    CRAs = ifelse(grepl("274", PackageID), "SESD", CRAs),
    CRAs = ifelse(grepl("276", PackageID), "SESD", CRAs),
    CRAs = ifelse(grepl("277", PackageID), "PC", CRAs),
    CRAs = ifelse(grepl("278", PackageID), "PC, OMD, ND", CRAs),
    CRAs = ifelse(grepl("280", PackageID), "PC", CRAs),
    CRAs = ifelse(grepl("281", PackageID), "OMD, ND", CRAs),
    CRAs = ifelse(grepl("282", PackageID), "PC", CRAs),
    CRAs = ifelse(grepl("284", PackageID), "PC", CRAs),
    CRAs = ifelse(grepl("285", PackageID), "PC", CRAs),
    CRAs = ifelse(grepl("286", PackageID), "LULCC", CRAs),
    CRAs = ifelse(grepl("288", PackageID), NA, CRAs),
    CRAs = ifelse(grepl("289", PackageID), "PC", CRAs),
    CRAs = ifelse(grepl("295", PackageID), "ND", CRAs),
    CRAs = ifelse(grepl("320", PackageID), NA, CRAs),
    CRAs = ifelse(grepl("344", PackageID), NA, CRAs),
    CRAs = ifelse(grepl("366", PackageID), "SESD", CRAs),
    CRAs = ifelse(grepl("368", PackageID), NA, CRAs),
    CRAs = ifelse(grepl("376", PackageID), "LULCC, PC", CRAs),
    CRAs = ifelse(grepl("378", PackageID), "LULCC", CRAs),
    CRAs = ifelse(grepl("383", PackageID), "PC, PP", CRAs),
    CRAs = ifelse(grepl("385", PackageID), "PC, PP", CRAs),
    CRAs = ifelse(grepl("389", PackageID), "PC", CRAs),
    CRAs = ifelse(grepl("395", PackageID), paste0("PC, ", CRAs), CRAs),
    CRAs = ifelse(grepl("396", PackageID), "ND, OMD", CRAs),
    CRAs = ifelse(grepl("501", PackageID), "LULCC", CRAs),
    CRAs = ifelse(grepl("502", PackageID), "LULCC", CRAs),
    CRAs = ifelse(grepl("503", PackageID), "LULCC", CRAs),
    CRAs = ifelse(grepl("504", PackageID), "LULCC", CRAs),
    CRAs = ifelse(grepl("505", PackageID), NA, CRAs),
    CRAs = ifelse(grepl("556", PackageID), "SESD", CRAs),
    CRAs = ifelse(grepl("557", PackageID), "OMD", CRAs),
    CRAs = ifelse(grepl("558", PackageID), "SESD", CRAs),
    # CRAs = ifelse(grepl("561", PackageID), "ND", CRAs),
    CRAs = ifelse(grepl("563", PackageID), NA, CRAs),
    CRAs = ifelse(grepl("569", PackageID), NA, CRAs),
    CRAs = ifelse(grepl("571", PackageID), "PC", CRAs),
    CRAs = ifelse(grepl("591", PackageID), NA, CRAs),
    CRAs = ifelse(grepl("584", PackageID), "SESD", CRAs),
    CRAs = ifelse(grepl("606", PackageID), "ND, OMD", CRAs),
    CRAs = ifelse(grepl("616", PackageID), "PC", CRAs),
    CRAs = ifelse(grepl("617", PackageID), "OMD, ND", CRAs),
    CRAs = ifelse(grepl("618", PackageID), "ND", CRAs),
    CRAs = ifelse(grepl("619", PackageID), "LULCC", CRAs),
    CRAs = ifelse(grepl("620", PackageID), "SESD", CRAs),
    CRAs = ifelse(grepl("621", PackageID), "OMD, ND", CRAs),
    CRAs = ifelse(grepl("623", PackageID), "LULCC", CRAs),
    CRAs = ifelse(grepl("624", PackageID), "OMD, ND", CRAs),
    CRAs = ifelse(grepl("626", PackageID), "PC", CRAs),
    CRAs = ifelse(grepl("627", PackageID), "PC", CRAs),
    CRAs = ifelse(grepl("628", PackageID), "SESD, DP, PC, PP, ND, OMD", CRAs),
    CRAs = ifelse(grepl("629", PackageID), "SESD", CRAs),
    CRAs = ifelse(grepl("630", PackageID), "OMD, ND", CRAs),
    CRAs = ifelse(grepl("631", PackageID), "SESD", CRAs),
    CRAs = ifelse(grepl("632", PackageID), "PP, ND, PC", CRAs),
    CRAs = ifelse(grepl("633", PackageID), paste0("PC, ", CRAs), CRAs),
    CRAs = ifelse(grepl("634", PackageID), "SESD", CRAs),
    CRAs = ifelse(grepl("635", PackageID), "SESD", CRAs),
    CRAs = ifelse(grepl("636", PackageID), NA, CRAs),
    CRAs = ifelse(grepl("637", PackageID), "PC", CRAs),
    CRAs = ifelse(grepl("Lerman", citation), "SESD, PC", CRAs),
    CRAs = ifelse(grepl("641", PackageID), "PC", CRAs),
    CRAs = ifelse(grepl("642", PackageID), "PC, SESD", CRAs),
    CRAs = ifelse(grepl("643", PackageID), "PC", CRAs),
    CRAs = ifelse(grepl("644", PackageID), "SESD", CRAs),
    CRAs = ifelse(grepl("645", PackageID), "SESD", CRAs),
    CRAs = ifelse(grepl("646", PackageID), "SESD", CRAs),
    CRAs = ifelse(grepl("647", PackageID), "SESD", CRAs),
    CRAs = ifelse(grepl("648", PackageID), "ND, LULCC", CRAs),
    CRAs = ifelse(grepl("649", PackageID), NA, CRAs),
    CRAs = ifelse(grepl("650", PackageID), "LULCC", CRAs),
    CRAs = ifelse(grepl("652", PackageID), "LULCC, OMD, ND, PC, SESD", CRAs),
    CRAs = ifelse(grepl("653", PackageID), "LULCC, PC, SESD", CRAs)
  )
```

```{r reference_pubs, include=FALSE}

# Add the CAP Top Ten publications to the relevant datasets. Some of the results
# returned by rcrossref have the wrong year or, in the case of Jenerette,
# bizarre text in the list of authors, so these need to be checked and edited in
# the output.

data_and_pubs <- vetted_data %>% 
  mutate(
    citation = ifelse(grepl("41.13", PackageID), paste0(citation, cr_cn("10.1890/11-0828.1", "text")), citation), # Bang et al 2012
    citation = ifelse(grepl("571", PackageID), paste0(citation, cr_cn("10.1890/11-0828.1", "text")), citation), # Bang et al 2012
    citation = ifelse(grepl("46.15", PackageID), paste0(citation, cr_cn("10.1016/j.landurbplan.2016.09.026", "text")), citation), # Banville et al 2017
    citation = ifelse(grepl("620", PackageID), paste0(citation, cr_cn("10.1007/s10980-015-0284-3", "text")), citation), # Jenerette et al 2016
    citation = ifelse(grepl("624", PackageID), paste0(citation, cr_cn("10.1007/s10021-014-9812-2", "text")), citation), # Hale et al 2015
    citation = ifelse(grepl("628", PackageID), paste0(citation, cr_cn("10.1002/eco.1457", "text")), citation), # Volo et al 2014
    citation = ifelse(grepl("632", PackageID), paste0(citation, cr_cn("10.1890/10-0758.1", "text")), citation), # Hall et al 2011
    citation = ifelse(grepl("633", PackageID), paste0(citation, cr_cn("10.1002/ecs2.1756", "text")), citation), # Bois et al 
    citation = ifelse(grepl("652", PackageID), paste0(citation, cr_cn("10.1002/ecs2.1826", "text")), citation), # Ripplinger et al 2017
    citation = ifelse(grepl("653", PackageID), paste0(citation, cr_cn("10.1002/ecs2.1826", "text")), citation) # Ripplinger et al 2017
  )
  
```


```{r generate_table, message=FALSE, results='asis', echo=FALSE}

# Table XYZ. Inventory of CAP LTER datasets housed in the LTER Network data
# repository hosted by the Environmental Data Initiative as of 2018-02-27. Where
# applicable, one or more relevant LTER Core Research Area(s) (CRAs) are noted
# (PP = Primary Production; PC = Populations and Communities; OMD = Organic
# Matter Dynamics; ND = Nutrient Dynamics; DP = Disturbance Patterns; LULCC =
# Land Use and Land Cover Change; SESD = Social-Ecological Systems Dynamics).
# Datasets that contributed to CAP's Top Ten publications are noted with the
# literature citation included with the dataset citation, but note that two of
# CAP's Top Ten publications Cook et al. 2012 and Zhang et al. are not featured
# in this inventory of datasets as the former is a literature review and the
# latter is model output.

# kable(formatted_data)
# pandoc.table(schedule, justify = c('left', 'left', 'left', 'left', 'left'))
# pandoc.table(schedule, split.cells = c(5, 10, 5, 10, 10))

set.alignment('left')
pandoc.table(data_and_pubs, split.table = Inf, missing = "")

```

